name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Ensure Functions Directory Exists
      run: |
        mkdir -p ./functions

    - name: Create and Activate Virtual Environment
      run: |
        cd functions
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r ./functions/requirements.txt

    - name: Set up Firebase CLI
      uses: w9jds/firebase-action@master
      with:
        args: login:ci --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

    - name: Deploy to Firebase
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: |
        . ./functions/venv/bin/activate
        firebase deploy --only functions
