name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Verify Python Installation
      run: python --version

    - name: Ensure Functions Directory Exists
      run: |
        mkdir -p ./functions

    - name: Create Virtual Environment
      working-directory: ./functions
      run: |
        python -m venv venv
        ls -l venv
        
    - name: Activate Virtual Environment and Install Dependencies
      working-directory: ./functions
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Firebase Functions
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}